[package]
name = "web3_ethereum_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = "2.0.14"
hex = "0.4.3"
tokio = {version = "1.43.0",features = ["full"]}
web3 = "0.19.0"
