[package]
name = "user_details"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }
yew = { version = "0.21.0", features = ["csr"] }


[lib]
crate-type = ["cdylib", "rlib"]