[package]
name = "hyperlane"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
ethers = { version = "2.0.14", features = ["rustls"] }
eyre = "0.6.12"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }



