[package]
name = "ipfs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.14",features = ["blocking","json","multipart"]}
serde = {version = "1.0.219",features = ["derive"]}
serde_json = "1.0.140"
tokio = {version = "1.44.1", features = ["full"]}

